### ISSUE TITLE
Percysnapshot hang on iframe page with map

### ISSUE THREAD

**Issue by yen-tt** [percy/percy-puppeteer#330]
Hello!
I'm using `percySnapshot()` function from the @percy/puppeteer package to create snapshots in the test scripts. Pages with iframe page that contains map, e.g. from Google or Mapbox API, seem to hang indefinitely and so the percy build is never finalized. There's no error in the terminal. I look through the code, and the issue seems to be specifically on the second page.evaluate call in `percySnapshot()`?

I have isolated the general page and test setup in this [repo](https://github.com/yen-tt/test-puppeteer) (map api key is omitted). when running `npm run percy`, the first snapshot for index.html is taken successfully. The second snapshot for iframe_test.html hangs.

**Comment by Robdel12** [comment]
Hey @yen-tt! This should be fixed in 1.0.0-beta.64 (https://github.com/percy/cli/releases/tag/v1.0.0-beta.64). Curious to hear how it works out 👀

**Comment by yen-tt** [comment]
Hi Robert! I updated percy/cli version to 1.0.0-beta.64 in the repo mentioned above and ran the script again. Seems like it's still hanging on the second snapshot

**Comment by Robdel12** [comment]
Hey @yen-tt! I tried to check out the repo and run it locally, but even without Percy I can't get the tests to run successfully:

```shell
node tests/percy/index.js
listening at http://localhost:5042
[percy] Percy is not running, disabling snapshots
(node:87982) UnhandledPromiseRejectionWarning: Error: No node found for selector: .HitchhikerFaqAccordion-toggle
    at Object.assert ( /scratch/answers-hitchhiker-theme/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click ( /scratch/answers-hitchhiker-theme/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async StandardPageNavigator.click ( /scratch/answers-hitchhiker-theme/tests/percy/standardpagenavigator.js:51:5)
    at async Photographer._captureUniversalSearch ( /scratch/answers-hitchhiker-theme/tests/percy/photographer.js:39:5)
    at async Photographer.captureSnapshots ( /scratch/answers-hitchhiker-theme/tests/percy/photographer.js:20:5)
    at async  /scratch/answers-hitchhiker-theme/tests/percy/index.js:28:3
(node:87982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:87982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yen-tt** [comment]
hey! I linked a small repo in the first comment if you could check it out instead. You should see that it's stuck on the second snapshot

**Comment by Robdel12** [comment]
Whoops! I did miss that in the original issue, sorry about that. It's a perfect repo -- looks like we have a regex that hangs the browser when serializing iframe relative URLs. I'm going to be working on refactoring/fixing that 👍🏼
